[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/kahing/goofys"
  version = "0.19.0"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "v0.3.0-1"

[[constraint]]
  branch = "master"
  name = "github.com/kubernetes-csi/drivers"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "6.0.5"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.13.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.11.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "gopkg.in/ini.v1"
  version = "1.38.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-ps"
